labels = {
    '247HC': '247 Hardcore',
    'A2REC': 'A2 Records',
    'ABUSEDDIGI': 'Abused_Recordingz',
    'ACR': 'Acid Reign',
    'ACT': 'Activa',
    'ACTDIGI': 'Activa',
    'ACTDRK': 'Activa Dark',
    'ACTSH': 'Activa Shine',
    '_': 'Actuation',
    'AT': 'Adrenaline_Tracks',
    'AFT3R': 'Afterlife Recordings (2) (AFT3R)',
    'AFTER': 'Afterlife Recordings (AFTER)',
    'AR': 'Aggressive Records',
    'ANY': 'Anarchy',
    'AM': 'Annihilate Music',
    'ASR': 'Antisocial Records',
    'APEX': 'APEX Records',
    'ARN': 'Arena_Label',
    'ARMADA': 'Armada Music',
    'AOC': 'Art of creation',
    '_': 'ARTificial',
    'ASTROPROJEKT': 'AstroFonik',
    'APHET': 'Audiophetamine',
    'ARM': 'Aurora Mortem records',
    'AVIO': 'AVIO',
    'AVIOCD': 'AVIO',
    'B2S': 'B2S',
    'BABY': 'Babys Back',
    '_': 'Bad Bitches',
    'BBR': 'Barbaric Records',
    'BF': 'Barong Family',
    'BD_': 'Bass-D Music',
    'BSC': 'Basscon Records',
    'BYMD': 'Be Yourself Music',
    'BYMCD': 'Be Yourself Music',
    'BKJN': 'Beter Kom Je Niet BKJN',
    'BIO': 'Bionic Bear',
    'BIT': 'Bit Italy',
    'BMR': 'Black Mirror Society',
    '': 'Black Reaper Records',
    'BBD': 'Blackbox Digital',
    'BLU': 'Blutonium Records',
    'BOMB': 'Bomb records',
    'BAB': 'Bombs And Bullets',
    'BT': 'Border Town',
    'BBR': 'Bounce Back Records',
    '_': 'Brachiale Musikk',
    'BS': 'Brandstichters',
    'BYT': 'Break The Rules',
    'BHM': 'Brennan Heart Music',
    'BMUT': 'Bring Me Up Tempo',
    'BTR': 'Bring the riot',
    'BSR': 'Broken Strain Records',
    'BRU': 'Brutale',
    'CM': 'Caput Mundi Records',
    'CRT': 'Cartel00 Records',
    'CAUSE': 'Cause Records',
    'CBK-': 'Cawfee Break',
    'CBK': 'Cawfee Break',
    'CUL': 'Chaotic Universe',
    'CFR': 'Chosen_Few_Recordz',
    'CLDG': 'Cloud 9 Dance',
    'CLDM': 'Cloud 9 Dance',
    '_': 'Cloud 9 Music',
    'CNN': 'CNNCTD',
    'CRD': 'CrunkD Records',
    'CRDCD': 'CrunkD Records',
    'CM': 'Crypton Music',
    'CMCD': 'Crypton Music',
    'CR.': 'Cyndium Records',
    'CR': 'Cyndium Records',
    'DF': 'D-Fence Records',
    'DD': 'Dark. Decent.',
    'DNMT': 'Danamite',
    'POLL': 'Dance Pollution',
    'DT': 'Dance Tunes BV',
    'DARKUL': 'Darkside unleashed',
    'DX': 'Dead_X',
    'DEATCHCHANT': 'Deathchant',
    'DEATCHCHANT_': 'Deathchant',
    'DCACWCOMP': 'Deathchant',
    'DM': 'Deathmatch Music',
    'DR': 'Delict Records',
    'DELEC': 'Delict Records',
    'DLM': 'Delirium Music',
    'DQX': 'Dequinox Music',
    'DTB': 'Derailed Trax black',
    'DTG': 'Derailed Trax grey',
    'DT': 'Derailed Traxx',
    'DVNT': 'DeviantMusic',
    '_': 'DF records',
    'DAR': 'Digital Abuse Records',
    'DIGI': 'Digital Age',
    'DGP': 'Digital Plague',
    'DGPFREE': 'Digital Plague',
    'DGPLP': 'Digital Plague',
    '_': 'Dimitri K Records',
    'DR': 'Dirty Rave',
    'DWX': 'Dirty workz',
    'DSBR': 'Disobey Records',
    'DSB': 'Disobey Records',
    'DSB_REC': 'Disobey Records',
    '_': 'DistroKid',
    'DJUORG': 'DJs United Orange Records',
    'DJURED': 'DJs United Red Records',
    'DJUZ': 'DJs United Zanzatraxx',
    'DOG': 'Dogfight Records',
    '_': 'Dort Music',
    'DKR': 'Drillkore Records',
    'DROKZ': 'Drokz',
    'DTS': 'DTS',
    'DMW': 'Dutch Master Works',
    'DMWH': 'Dutch Master Works Hybrid',
    'DWARF': 'Dwarf Records',
    'ESU': 'Eastside Underground',
    'ESU_': 'Eastside Underground',
    'ELFX': 'Electric Fox',
    '_': 'Element',
    'ELPAU': 'Elitepauper Publishers',
    'ELL': 'Ellivium Music',
    'EMF': 'EMFA Music',
    'EMFA': 'EMFA Music',
    'EHM': 'Empire Hardcore Music',
    'EOL': 'End of line',
    'ENZYME K7': 'Enzyme K7',
    'ENZYME': 'Enzyme Records',
    'CDE': 'Enzyme Records',
    'ENZYMEVIP': 'Enzyme VIP',
    'ENZYMEX': 'Enzyme X',
    'ENZYMEX_': 'Enzyme X',
    '_': 'Epic Local',
    'PMIEP': 'Essential Platinum',
    'ETY': 'Eternity',
    'EFR': 'Euphoric Frenchcore',
    'EM': 'Euphoric Madness',
    'ER': 'Evolve AU',
    'EXT': 'Exit Records',
    'EXT': 'Exitus Hardcore',
    'EX': 'Exode Records',
    'FYF': 'Face Your Fear',
    'FE': 'Fe Records',
    '_': 'Fear FM',
    'FLM': 'Fear Less Music',
    '_': 'Filthy Face Records',
    'FISHRICE': 'Fish and Rice Recordings',
    'FLSM': 'Foolish',
    'FLSMA': 'Foolish',
    'FOOLISH': 'Foolish',
    'FWXXDIGI': 'Footworxx',
    'FR': 'Freestyle',
    'FCD': 'Frenchcore Decadence',
    'FWWSVP': 'Frenchcore SVP',
    'FWWSGL': 'Frenchcore Worldwide',
    'FKR': 'FrenchKickz Records',
    '_': 'FRFC Records',
    '_': 'FROSTBYTE',
    'FBR': 'Fucking Bastard Records',
    'FUSION': 'Fusion records',
    'SICKRAGE': 'Future Sickness Recordings',
    'FVCK': 'FVCK GENRES',
    'GBD': 'Gearbox Digital',
    'GBE': 'Gearbox Euphoria',
    'GHD': 'Gearbox Hard Dance',
    'GBO': 'Gearbox Overdrive',
    'GBR': 'Gearbox Revolutions',
    'GTM': 'GEE thAng Music',
    'GEN': 'Genosha One Seven Five',
    'GENOSHA': 'Genosha Records',
    'GPF': 'GPF Recordz',
    'GREAZY': 'GPF Recordz',
    'GTR': 'Guillotine Recordings',
    'HAKCDG': 'Handkcuf Records',
    'HAKCD': 'Handkcuf Records',
    'HAKCSP': 'Handkcuf Records',
    'H2O': 'H2oh Recordings',
    'HMRG': 'Hard Music Records Gold',
    'HMRR': 'Hard Music Records Raw',
    'HWS': 'Hard With Style',
    '_': 'Hardcore Blasters',
    'JUMP': 'Hardcore Blasters Jump',
    'HCCR': 'Hardcore Canada Records',
    'HF': 'Hardcore France',
    'HCMALICE': 'Hardcore Malice',
    '_': 'Hardcore Mayhem',
    'HR': 'Hardcore Riot',
    'TCDR-': 'HARDCORE TANOC',
    'HC': 'Hardstyle Creation',
    'HSF': 'Hardstyle France',
    'HTJP': 'Hardtek.JP',
    '_': 'HARRIS & FORD',
    'HCMF': 'HCMF',
    'HDF-': 'Head Fuck Negative',
    'HDF': 'Head Fuck Records',
    'HDFDIGI': 'Head Fuck Records Digital',
    'H4H': 'Heart for Hard',
    'HELLS': 'Hells Recordings',
    'HERESY': 'HERESY',
    'DISCIPLES': 'Heresy Disciples',
    'HBR': 'Hexablast Records',
    'HKV': 'Hong Kong Violence',
    'IAF': 'I Am Frenchcore',
    'IAMF': 'I Am Frenchcore',
    'I_Am_Frenchcore_': 'I Am Frenchcore',
    'IAH': 'I AM HARDSTYLE',
    'IAHA': 'I AM HARDSTYLE - Amplify',
    'ILB': 'I Love Beats',
    'ID': 'Identity Records',
    'IGD': 'Ignition Digital',
    'ERPN_': 'Ignored Records',
    '_': 'IGor Records',
    'IMPCS': 'Important Corestyle',
    'IMPHC': 'Important Hardcore',
    'IMPHCLTD': 'Important Hardcore Limited',
    '_': 'Independent',
    'i': 'Indus3 Records',
    'ISRD': 'Industrial Strength',
    'IFR': 'Infected Records',
    'INFEX': 'InfeXious Raw',
    '_': 'Inner Rage Productions',
    'ISX': 'Insaniax',
    'INT': 'Intents Records',
    'IRS-': 'Invaders & Science',
    'IR': 'Invaders Records',
    'INV': 'Invaissor Records',
    'II': 'Irrational Impulses',
    'II_': 'Irrational Impulses',
    'ITAL': 'Italian Hardstyle',
    'JB-BPINT': 'Jabroer',
    'JDXMUSIC': 'JDX Music',
    'K1R': 'K1 Recordz',
    'KKR': 'KarmaKontra Records',
    'KKRC': 'KarmaKontra Records',
    'KKV': 'KarmaKontra Records',
    'KKE': 'KarmaKontra Records',
    'KRE': 'KarmaKontra Records',
    'KKRMX': 'KarmaKontra Records',
    'KARNAGE': 'Karnage Records',
    'KARNAGEDIGITA': 'Karnage Records',
    'KARNAGEDIGITAL ': 'Karnage Records',
    'KIU': 'Keep it up',
    'KTRAR': 'Keeping The Rave Alive',
    '_': 'KETA RECORDS',
    'KNOR': 'KNOR Records',
    '_': 'Kontor Records',
    'KRH': 'Kurrupt Recordings Hard',
    '_': 'LASER [BNL]',
    'LBSK': 'Le Bask Records',
    'LTD': 'Lethal Theory',
    'LVL': 'LEVEL',
    'LCM': 'Lose Control Music',
    '_': 'LOVE 4 HARD',
    'LVHz': 'Love Hz',
    'LOV': 'LoverLoud',
    'LINC': 'Lowroller Inc',
    'LT': 'Luca Testa',
    'LT_': 'Luca Testa',
    '_': 'Madback Records',
    '_': 'Major Smoke Records',
    'MDL': 'Mandala',
    '_': 'Manneken Pis',
    '_': 'Mark With a K',
    'MASIF': 'Masif',
    'MD': 'Massive Dynamic',
    'MOHDIGI': 'Masters Of Hardcore',
    '_': 'MAXXIMIZE',
    ''
    'MMT': 'Meccano Music',
    'MRV': 'Megarave Records',
    '_': 'Midify',
    'MIM': 'Minus Is More',
    'MINUS': 'Minus Is More',
    '_': 'Monolith',
    'MC': 'Monstercat',
    'MONSTER': 'Monsters Of Terrorcore Records',
    'MOR': 'More Music And Media',
    'MOTHDATA': 'Motormouth Records',
    'IVEX': 'Mr. Ivex Auditory',
    '_': 'Mvtate',
    'MTIU': 'My tempo is uptempo',
    'MWY': 'My Way',
    'MYM': 'My Way Music',
    'NEGA': 'Negative Audio',
    'NEGACD': 'Negative Audio',
    'NERKOLOG!K': 'Nekrolog1k Recordings',
    'NERKOLOG1K': 'Nekrolog1k Recordings',
    'NEO': 'Neophyte records',
    'NMR': 'Neox Music Records',
    'NMR_': 'Neox Music Records',
    'NDR': 'New Dawn Records',
    'NWO': 'New World Order Records',
    '_': 'Nexchapter',
    'NC': 'Next Chapter',
    'NGREC': 'NG Recordings',
    '_': 'Nightbreed Nocturnal',
    'NBQ': 'Nightbreed Records',
    '_': 'NightCode Recordings',
    'NER': 'No Es Ruido',
    'NCREC': 'Noisecontrol Records',
    'NCRECCD': 'Noisecontrol Records',
    'NKR': 'Noisekick Records',
    'NOISJ': 'Noize Junky',
    '_': 'Northern Outpost',
    'N4A': 'Nothing 4 All',
    '_': 'NOTYPE',
    '_': 'NRGY Music',
    'NUTTY': 'Nutty Traxx',
    'OBVN': 'Oblivion Music',
    'OBLIVION': 'Oblivion Underground Recordings',
    'OFFRAGE': 'Offensive Rage',
    'OFF': 'Offensive Records',
    'OMN': 'Omny Lab',
    '_': 'One More Rep',
    'ONESEVENTY': 'One Seventy',
    'HWS': 'Origins',
    'OTHCD': 'Othercide',
    'PR': 'Partyraiser Records',
    'PCR': 'Peacock Records',
    '_': 'Peacocks Exclusives',
    'PIJN': 'PIJN',
    'PKB': 'Pink Beats',
    'PKBCD': 'Pink Beats',
    'PX': 'PL4N3T X',
    'POW': 'Pow records',
    'POW-': 'Pow records',
    'PHR': 'Power Hour Records',
    'PNR': 'Prague Nightmare Records',
    'PCR': 'Project Chaos Records',
    '_': 'Project Red',
    'PROTEST': 'Promo Test',
    'PRSPCT': 'Prospect',
    'PRSPCTSUB': 'Prospect',
    'PRSPCTXTRM': 'Prospect',
    'PRSPCTRVLT': 'Prospect',
    'PRSPCTXTRMDIGI': 'Prospect',
    '_': 'Prototypes Records',
    '_': 'Psychik Genocide',
    'PM': 'Pure Massive Records',
    'PLM': 'Pussy Lounge Music',
    'Q': 'QDance',
    'QDIG': 'QDance',
    'NEXT': 'Qdance presents NEXT',
    'QORE': 'QORE',
    'QULT': 'Qult Records',
    'R909-': 'Randy909',
    'RAPT': 'Rapture Records',
    'RAVE': 'Rave Alert',
    'RC': 'Rave Culture',
    'RG': 'Rave Generation',
    'RID': 'Rave Instinct',
    'RBR': 'REBiRTH Events Records',
    'REBL': 'Rebl Records',
    'RLNTDIGI': 'Relentless Digital',
    'RLNT': 'Relentless Digital',
    '_': 'Relianze',
    '_': 'Remz Roster',
    'REVR': 'Revealed Recordings',
    'REV': 'Revloxist',
    '_': 'ROQ n Rolla',
    'ROT': 'Rotterdam Records',
    'ROTSP': 'Rotterdam Records',
    'ROTC': 'Rotterdam Records',
    'ROT_': 'Rotterdam Records',
    'ROUGHR': 'Rough Recruits',
    'ROUGH': 'Roughstate',
    'RSR': 'RSLVD Records',
    'RSU': 'RSU Records',
    'RV': 'Rude Vibes',
    'REX': 'Ruffex',
    'REXDF': 'Ruffex',
    'RUFFA': 'Ruffneck Anomalies',
    'RUF': 'Ruffneck Records',
    'STRAX': 'S-Trax',
    'SSR': 'Savage Squad Recordings',
    'SSROZ': 'Savage Squad Recordings OZ',
    'SCAN': 'Scantraxx',
    'BLACK': 'Scantraxx Black',
    'SCARB': 'Scantraxx Carbon',
    'EVO': 'Scantraxx Evolutionz',
    'EVOCD': 'Scantraxx Evolutionz',
    'GLOBAL': 'Scantraxx Global',
    'ITAL': 'Scantraxx Italy',
    'PRSPX': 'Scantraxx Prospexx',
    'SCREL': 'Scantraxx Reloaded',
    'SSL': 'Scantraxx Silver',
    'SEADIGI': 'Sealand Recordings',
    'SEFA': 'Sefa Music',
    'SM': 'Sefa Music',
    'SMR': 'Seismic Raw',
    'SMCCD': 'Seismic Records',
    'SM': 'Shadow Mask',
    'SHARP': 'Sharp As A Knife Records',
    'SUAR': 'ShutUpAndRave',
    'SR': 'SickCore Records',
    '_': 'Sinphony',
    'SK': 'Skink',
    'SMH': 'Smash',
    'SMASH': 'Smash Records',
    'SSO': 'Smashed Society',
    'SPM': 'Snakepit Music',
    '_': 'Snowbass Records',
    '_': 'Sound of Hardcore',
    '_': 'Speedcore Italia',
    'SPEQTRUM': 'Speqtrum Music',
    'SPIKEPROTEIN': 'Spike Protein',
    'SR_': 'Spinning records',
    'SOH': 'Spirit of Hardstyle',
    'SM': 'Spline Music',
    'SPOON': 'Spoontech Records',
    'SOA': 'State Of Anarchy',
    'SGR': 'Static Gravity Records',
    'SUB': 'Subground',
    'SSR...': 'Super Solid',
    'SNR': 'Supernova Records',
    'SPK': 'Superplastik',
    'SIN': 'Supreme Intelligence',
    'SOC': 'Symphony of Core',
    'SOC_': 'Symphony of Core',
    'SYSTEM': 'System outage',
    'TILLT': 'T!LLT',
    'TILLTG': 'T!LLT',
    'TILLTLBL': 'T!LLT',
    'TCLABS': 'TC Labs',
    'TCLABSPRO': 'TC Labs',
    'TCREC': 'TC Records',
    'TMR': 'Terror Machine Records',
    'TDR': 'Terrordrang Records',
    'TERRORHEADS': 'Terrorheads',
    'TEX_': 'Texcore',
    'TEX': 'Texcore',
    'TBR': 'The boss records',
    'CATID': 'The Funky Cat',
    'TMS': 'The Magic Show',
    'T3RDM': 'The Third Movement',
    'TBYTE': 'Therabyte',
    'THER': 'Theracords',
    'TCC': 'Theracords Classics',
    'LABS': 'Theracords Labs',
    'TIF': 'This Is Frenchcore Recordings',
    'TIH?': 'This is hardcore',
    'TIH': 'This Is Hardstyle',
    'TIT': 'This is Terror',
    'TIUR': 'This is uptempo records',
    '_': 'Thorax Productions',
    'TDM': 'Thunderdome Music',
    '?': 'Thunderdome Records',
    '_': 'Titanic',
    'TOFF': 'TOFF Music',
    '_': 'ToXicCore Rec',
    'TRAX': 'Traxtorm',
    '_': 'Triple G Records',
    'TSR': 'Triple Six Records',
    '_': 'Triplex Records',
    '_': 'Triton',
    '_': 'Twisted sound records',
    'UCSTR': 'U Cant Stop The Rave',
    'UBR': 'Unbreakable Records',
    'UGR': 'Underground Gangsta Records',
    'UIPR': 'Underground Industry Records',
    'UGTC': 'Underground Tekno',
    'UGTEP': 'Underground Tekno',
    'UGTCAL': 'Underground Tekno',
    'UNFR': 'Unfold Music',
    'UNITE': 'Unite Records',
    'UR': 'Unleashed Records',
    'UNLR': 'Unlocked Records',
    'UPR': 'Upcoming Records',
    'UHR': 'Uptempo Hardcore Records',
    'UITT': 'Uptempo is the tempo records',
    'VYT': 'Vyolet',
    'WFREC': 'War Force Records',
    'WMD': 'Warner Music Denmark',
    'WER': 'WE R',
    'WERR': 'WE R RAW',
    'WERT': 'WE R Tomorrow',
    '_': 'WLFPCK',
    'WLF': 'Wolf Clan',
    'WOLV': 'Wolvpack Recordings',
    '_': 'Worldwidedomination Records',
    'WUZE': 'Wuze Records',
    'XBONE': 'X-Bone',
    'XQH': 'X-Qlusive Holland Records',
    'XRATE': 'X-Rate Records',
    'XRAW': 'X-RAW',
    'XTR': 'X-Tinction Recordz',
    'X7M': 'X7M',
    'XBREED': 'XBREED Records',
    'XPLODED': 'Xploded Music Limited',
    'XPN': 'XPN Music',
    'XAV': 'Xtreme Audio Violence',
    'XTREME': 'Xtreme Records',
    'XTRM': 'XTRMN8 RECORDS',
    'YO': 'Yosuf',
    'YGR': 'Young Guns Records',
    'ZZF': 'Zanza Files',
    'ZLB': 'Zanzalabs',
    '_': 'Zero Day Records',
    'ZD': 'Zoo Digital',
    'ZOO': 'Zoo Records',
    'REV': 'Zoo Records',
}
