name: Python tests and coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        coverage run --source=. -m unittest discover -p "*Test.py"
        coverage html

    - name: Prepare GitHub Pages folder
      run: |
        mkdir -p site/coverage
        cp -r htmlcov/* site/coverage/
        cp README.md site/README.md
        cat <<EOF > site/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="refresh" content="0; url=README.md" />
    <title>Redirecting...</title>
  </head>
  <body>
    Redirecting to README.md...
  </body>
</html>
EOF

    - name: Deploy full site (README + coverage)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./site
        force_orphan: true
        enable_jekyll: true
