name: Frontend tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10 --activate

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run vitest
        run: pnpm test
